# pubspec.yaml

name: ensf_mobile
description: "Professional Banking Mobile Application with Backend Integration"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  provider: ^6.1.4

  # HTTP & API Integration
  http: ^1.3.0
  dio: ^5.4.2  # Alternative HTTP client with interceptors
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  # Security & Authentication
  local_auth: ^2.1.8  # Biometric authentication
  crypto: ^3.0.3      # For encryption/hashing
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  
  # File & Image Handling
  image_picker: ^1.0.7
  file_picker: ^8.0.3
  
  # Network & Connectivity
  connectivity_plus: ^6.0.3
  
  # Device Info
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  
  # Utilities
  intl: ^0.19.0           # Internationalization
  uuid: ^4.3.3            # UUID generation
  equatable: ^2.0.5       # Value equality
  
  # UI Components
  flutter_svg: ^2.0.10    # SVG support
  cached_network_image: ^3.3.1  # Image caching
  shimmer: ^3.0.0         # Loading animations
  
  # QR Code (for transactions) - UPDATED TO COMPATIBLE VERSIONS
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0   # REPLACED qr_code_scanner with mobile_scanner
  
  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # Fonts (if using custom fonts in addition to Google Fonts)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic